spring.application.name=tontine-manager

server.port=8080

logging.level.org.springframework=INFO
logging.level.com.tontineApp.tontine_manager=DEBUG



spring.jpa.show-sql=true

spring.security.oauth2.client.registration.github.client-id=Ov23liNWAipcNvwsiIOe
spring.security.oauth2.client.registration.github.client-secret=af2bc2bb0fd8f063b94b4cba8286ef01aae2c622


