spring.application.name=tontine-manager

server.port=9000

logging.level.org.framework=INFO
logging.level.com.tontineApp.tontine_manager=DEBUG

logging.file.name=application.log
org.springframework.boot.web.embedded.tomcat=true

custom.logging.enabled=true
custom.logging.level=DEBUG


spring.jpa.show-sql=true



