spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tontine
    username: postgres
    password: francois
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true